[build]
builder = "nixpacks"
buildCommand = "python manage.py tailwind install && python manage.py tailwind build && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn core.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 