[build]
builder = "nixpacks"
buildCommand = "python3 manage.py tailwind install && python3 manage.py tailwind build && python3 manage.py collectstatic --noinput"

[deploy]
startCommand = "python3 manage.py migrate && gunicorn core.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100