# Generated by Django 5.2.1 on 2025-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_field',
            field=models.CharField(default='', max_length=255),
        ),
    ]
