# Generated by Django 5.2.1 on 2025-05-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_field',
        ),
    ]
