# Generated by Django 5.2.1 on 2025-05-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_description_product_barcode_and_more'),
    ]

    operations = [
    ]
