# Generated by Django 5.2.1 on 2025-05-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Manager',
        ),
    ]
